name: Build

on: [push, pull_request]
env:
  WAF_FLAGS: -T debug --disable-warns --prefix=build_hl2

jobs:
  deps:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-2019
        bits: ['', '--64bits']
        android: ['']
        include:
          - os: ubuntu-20.04
            bits: ''
            android: '--android=armeabi-v7a-hard,4.9,21 --togles'
        exclude:
          - os: macos-latest
            bits: ''
    uses: ./.github/workflows/deps.yml
    with:
      os: ${{ matrix.os }}
      bits: ${{ matrix.bits }}
      android: ${{ matrix.android }}
      linux-deps: libopenal-dev libpng-dev libjpeg-dev libfreetype6-dev libfontconfig1-dev libcurl4-gnutls-dev libsdl2-dev zlib1g-dev libbz2-dev libedit-dev
      macos-deps: sdl2

  build:
    needs: deps
    environment: production
    runs-on: ${{ needs.deps.outputs.os }}

    strategy:
      fail-fast: false
      matrix:
        deps: ${{ needs.deps.outputs.* }}
        flags: ['', '-d']

    steps:
      - name: Configure
        run: ./waf configure ${{ matrix.deps.bits }} ${{ matrix.deps.android }} ${{ matrix.deps.flags }} $WAF_FLAGS

      - name: Build ${{ matrix.deps.os }}
        run: ./waf install --strip-to-file

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: ${{runner.os}}${{matrix.deps.bits}}${{matrix.deps.flags}}${{matrix.deps.android}}
          path: |
            build_hl2
      # TODO
      #- name: Upload debug symbols
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: Debug-${{runner.os}}${{matrix.bits}}${{matrix.flags}}${{matrix.android}}
      #    path: |
      #      build_debug

