name: Build

on: [push, pull_request]

jobs:
  build-linux-i386:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build linux-i386
      run: |
        scripts/build-ubuntu-i386.sh -u

  build-linux-amd64:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build linux-amd64
      run: |
        scripts/build-ubuntu-amd64.sh -u

  build-android-armv7a:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build android-armv7a
      run: |
        scripts/build-android-armv7a.sh

  build-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug -u
        ./waf.bat build

  build-windows-amd64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug -8 -u
        ./waf.bat build

  build-dedicated-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug -dl
        ./waf.bat build

  build-dedicated-windows-amd64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug -dl -8
        ./waf.bat build

  build-dedicated-linux-i386:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated linux-i386
      run: |
        scripts/build-ubuntu-i386.sh -dl

  build-dedicated-linux-amd64:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated linux-amd64
      run: |
        scripts/build-ubuntu-amd64.sh -dl

  build-macos-amd64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build macos-amd64
      run: |
        scripts/build-macos-amd64.sh -u

  build-dedicated-macos-amd64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated macos-amd64
      run: |
        scripts/build-macos-amd64.sh -dl
